### PR TITLE
Finished draft of penguin-biplots.Rmd

### PR DESCRIPTION
**Pull request by friendly**
This is proposed as a new vignette in the package.

### CODE REVIEW

**Comment by friendly** [comment]
If you agree, I'll move this into vignettes on my fork and re-style it as a vignette

**Comment by allisonhorst** [comment]
Hi Michael - 

Thanks for your biplot vignette for palmerpenguins! This is an exciting use case and we appreciate seeing these examples of the data being used "in the wild". 

In an effort to make the palmerpenguins package as lightweight as possible we're in the process of minimizing dependencies and have decided to link to external posts/vignettes in the 'User-contributed examples' section instead of incorporating them into the package directly. 

Would you be willing to publish elsewhere then do a PR to [this file](https://github.com/allisonhorst/palmerpenguins/blob/master/vignettes/articles/user_contributions.Rmd) to add it as our first user contributed vignette?

Thanks so much,
Allison & Alison

**Comment by friendly** [comment]
OK, I've done that & published it as https://rpubs.com/friendly/penguin-biplots

But it is now too much work to keep my fork consistent with yours, so I updated `user_contributions.Rmd` on my fork.  Here it is for you to fetch

https://github.com/friendly/palmerpenguins/blob/master/vignettes/articles/user_contributions.Rmd

**Comment by friendly** [comment]
I'm continuing to work on another example using the penguins data, for my own purposes and severing this from your palmerpenguins package, as you requested.
(FYI: I'm planning to use this in a book or articles with the theme of "visualizing multivariate linear models")

Yet, there remains a difficulty in how I refer to/access the `penguins` data in my scripts/examples because the package is not on CRAN.

In my local version, I can use

```{r}
data(penguins, package="palmerpenguins")
```

but this is not reproducible if the package is not on CRAN. I suppose I could use an `install_github()` here.

**Comment by allisonhorst** [comment]
Hi Michael - 

palmerpenguins isn't on CRAN yet, so in the meantime it is [installed through github](https://github.com/allisonhorst/palmerpenguins#installation). 

We are excited to see and include user-submitted examples with the penguins. 

The link for your second vignette (MANOVA & HE plots) submitted in [issues](https://github.com/allisonhorst/palmerpenguins/issues/35#issue-641297899) unfortunately throws a 404 error. 

We would really appreciate it if you can create a PR to [this file](https://github.com/allisonhorst/palmerpenguins/blob/master/vignettes/articles/user_contributions.Rmd) containing the two correct links and your authorship information. 

-Allison

**Comment by friendly** [comment]
Hi
I fixed the typo problem with the second vignette by renaming the file on Rpubs to what it is in `user_contributions.Rmd`

https://rpubs.com/friendly/penguin-manova

I can't easily do a PR without first restarting my fork, so please use what I sent before.

    ### Links to user-contributed examples, posts and vignettes: 

    * [Penguins data: Multivariate EDA](https://rpubs.com/friendly/penguin-biplots)
        + Author: Michael Friendly
        + Description: These examples show the use of multivariate exploratory visualization methods -- principal component analysis and biplots -- to understand the relations among variables in the penguins data set.

    * [Penguins data: MANOVA and HE plots](https://rpubs.com/friendly/penguin-manova)
        + Author: Michael Friendly
        + Description: This vignette illustrates the use of MANOVA, HE plots and canonical discriminant analysis in the analysis of the Palmer penguins data.

**Comment by allisonhorst** [comment]
Links added to user-contributed examples

**Pull request closed without merging**
